spring:
  data:
    mongodb:
      host: ${mongo.host}
      port: ${mongo.port}
      username: ${mongo.username}
      password: ${mongo.passwd}
      database: ${mongo.db}
      authenticationDatabase: admin
  redis:
    database: 0
    host: ${redis.host}
    port: 6379
    password: ${redis.passwd}
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000


biz:
  jwt:
    secret: 123456