spring:
  data:
    mongodb:
      uri: ${mongodb.uri}

  redis:
    database: 0
    host: ${redis.host}
    port: 6379
    password: ${redis.passwd}
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000
  datasource:
    url: ${mysql.uri}
    username: ${mysql.username}
    password: ${mysql.passwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.milchstrabe.sun.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


