spring:
  data:
    mongodb:
      uri: ${mongodb.uri}
  redis:
    database: 0
    host: ${redis.host}
    port: 6379
    password: ${redis.passwd}
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000

